### ISSUE TITLE
Error in browser's console when component redirects after a handled store action

### ISSUE THREAD

**Issue by pragmadash** [catberry/catberry#165]
Here is a stacktrace:
```
Uncaught (in promise) TypeError: Cannot read property 'routingContext' of null
 at DocumentRenderer._updateStoreComponents (http://novosibirsk.flamp.me:3001/bundle.js:13971:54)
 at http://novosibirsk.flamp.me:3001/bundle.js:14002:16DocumentRenderer._updateStoreComponents @ DocumentRenderer.js:710(anonymous function) @ DocumentRenderer.js:741
```

**Comment by pragmadash** [comment]
Trying to reproduce it [here](https://github.com/pragmadash/catberry-redirect-error-test) but it's not successful so far.
