### ISSUE TITLE
New error after installation v5.2.2

### ISSUE THREAD

**Issue by slonofanya** [catberry/catberry#172]
Commands:
npm i catberry (5.2.2)
npm i catberry-assets

After:
npm run debug

Output:
some normal logs
.... AND:
[ERROR] catberry - { [Error: watch ENOSPC] code: 'ENOSPC', errno: 'ENOSPC', syscall: 'watch' }
Error: watch ENOSPC
    at exports._errnoException (util.js:746:11)
    at FSWatcher.start (fs.js:1172:11)
    at Object.fs.watch (fs.js:1198:11)
    at createFsWatchInstance (/var/www/site/node_modules/catberry/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/var/www/site/node_modules/catberry/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at EventEmitter.NodeFsHandler._watchWithNodeFs (/var/www/site/node_modules/catberry/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at EventEmitter.NodeFsHandler._handleDir (/var/www/site/node_modules/catberry/node_modules/chokidar/lib/nodefs-handler.js:403:23)
    at EventEmitter.<anonymous> (/var/www/site/node_modules/catberry/node_modules/chokidar/lib/nodefs-handler.js:450:19)
    at EventEmitter.<anonymous> (/var/www/site/node_modules/catberry/node_modules/chokidar/lib/nodefs-handler.js:455:16)
    at FSReqWrap.oncomplete (fs.js:95:15)
error: { [Error: watch ENOSPC] code: 'ENOSPC', errno: 'ENOSPC', syscall: 'watch' }

**Comment by pragmadash** [comment]
It seems like your filesystem or directory is protected for writing or the user of the process does not have permission to write on this file system or directory.

ENOSPC means "Error no space on the partition".
Anyway, it's not a Catberry issue, it's related to [chokidar](https://github.com/paulmillr/chokidar).

I recommend you to post an issue [there](https://github.com/paulmillr/chokidar) and describe your OS and Node version.

**Comment by slonofanya** [comment]
I applied solution from here: http://stackoverflow.com/questions/16748737/grunt-watch-error-waiting-fatal-error-watch-enospc 
And error is disappeared. But watching isn't working now.

**Comment by slonofanya** [comment]
Maybe it will be helpful: i execute "npm run debug" in vagrant on shared folders.

**Comment by pragmadash** [comment]
I have no idea what's the problem, but it's definitely not a problem with Catberry itself and the watching works well using the real OS instead a vagrant container. So, my answer will be the same, you should ask chokidar guys about the problems with vagrant container environment.

Please try to create an example using chokidar directly with watching a file. I'm sure it won't work. So, you will have an example for creating a [chokidar issue](https://github.com/paulmillr/chokidar/issues).

**Comment by slonofanya** [comment]
I started on host machine and it works. Let's close the issue.
