### ISSUE TITLE
Error did not show the file and line position

### ISSUE THREAD

**Issue by ucin** [catberry/catberry#202]
When I had a syntax error on my component, the log print didn't show the actual line.

![image](https://cloud.githubusercontent.com/assets/387567/10184232/e626c45e-6763-11e5-9952-bd425404f618.png)

Is it possible to find the exact position of error where the error has actually occurred?

**Comment by pragmadash** [comment]
Hi @ucin !
It seems like you have a syntax error in some of your templates. Since templates are using [vm](https://nodejs.org/api/vm.html) module of node.js for executing on the server, the error position/file can't be displayed. It's up to template engine and its compiler to determine and show the error.

What template engine are you using?

**Comment by ucin** [comment]
@pragmadash, thank you for quick response.
I'm using handlebar template.

**Comment by pragmadash** [comment]
@ucin, I'll do research what we can do with such errors and I'll let you know.

**Comment by ucin** [comment]
Awesome @pragmadash!
Yep, this should be tagged as `enhancement`, I always can run a linting tool to find the error.

**Comment by pragmadash** [comment]
It seems like newer Handlebars compiler now shows nice output for its errors, like:
```
[2016-01-31 13:43:57.129] [ERROR] catberry - [Error: Parse error on line 2:
...llo, {{#who}}!</h1>
----------------------^
Expecting 'INVERSE', 'OPEN_ENDBLOCK', got 'EOF']
Error: Parse error on line 2:
...llo, {{#who}}!</h1>
----------------------^
Expecting 'INVERSE', 'OPEN_ENDBLOCK', got 'EOF'
    at Object.parseError (/Users/pragmadash/Desktop/catberry-test/node_modules/catberry-handlebars/lib/vendors/handlebars.js:987:13)
    at Object.parse (/Users/pragmadash/Desktop/catberry-test/node_modules/catberry-handlebars/lib/vendors/handlebars.js:1039:24)
    at HandlebarsEnvironment.parse (/Users/pragmadash/Desktop/catberry-test/node_modules/catberry-handlebars/lib/vendors/handlebars.js:1598:19)
    at precompile (/Users/pragmadash/Desktop/catberry-test/node_modules/catberry-handlebars/lib/vendors/handlebars.js:1996:19)
    at HandlebarsEnvironment.hb.precompile (/Users/pragmadash/Desktop/catberry-test/node_modules/catberry-handlebars/lib/vendors/handlebars.js:3057:14)
    at TemplateProvider.compile (/Users/pragmadash/Desktop/catberry-test/node_modules/catberry-handlebars/lib/TemplateProvider.js:51:26)
    at /Users/pragmadash/Projects/catberry/lib/loaders/ComponentLoader.js:333:36
[2016-01-31 13:43:57.130] [ERROR] catberry - [Error: Parse error on line 2:
...llo, {{#who}}!</h1>
----------------------^
```

I think it resolves the issue.
