### ISSUE TITLE
Error while starting the project with some route rules

### ISSUE THREAD

**Issue by reenko** [catberry/catberry#208]
Error while starting the project with route rule sush as `expression: '/test/:var[]'`:
```
[ERROR] catberry - [TypeError: Cannot call method 'isLevelEnabled' of undefined]
TypeError: Cannot call method 'isLevelEnabled' of undefined
    at Logger.(anonymous function) (.../node_modules/catberry/node_modules/log4js/lib/logger.js:74:36)
    at tryCallOne (.../node_modules/catberry/node_modules/promise/lib/core.js:37:12)
    at /.../node_modules/catberry/node_modules/promise/lib/core.js:103:15
    at flush (.../node_modules/catberry/node_modules/promise/node_modules/asap/raw.js:50:29)
    at process._tickCallback (node.js:419:13)
```

**Comment by pragmadash** [comment]
It seems like the problem is not connected with route rules. I can't reproduce the problem using the last version of Catberry and its dependencies.
