### ISSUE TITLE
npm run debug-win Error

### ISSUE THREAD

**Issue by Levinskis** [catberry/catberry#340]
Running the command `npm run debug-win`  ends with following traceback:
```
\node_modules\catberry\lib\promises\promiseHelper.js:13
                return function(...args) {
                                ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\Aleksandrs\Documents\Projects\iespiedplate.lv\node_modules\catberry\lib\promises\fs.js:4:16)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
 ```

**Comment by pragmader** [comment]
Please update your version of Node.js to the latest one.
